export interface Car {
  id: number
  name: string
  make: string
  model: string
  year: number
  price: number
  mileage: number
  bodyType: string
  fuelType: string
  transmission: string
  safetyRating: number
  horsepower: number
  mpg: number
  color: string
  image: string
  seats: number
  variant: string
  matchPercentage: number
  scoreBreakdown: {
    budget: number
    efficiency: number
    safety: number
  }
}

export const carData: Car[] = [
  {
  'id': 1,
  'name': 'Tata Safari',
  'make': 'Tata',
  'model': 'Safari',
  'year': 2024,
  'price': 1080251,
  'mileage': 12.4,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'Automatic',
  'safetyRating': 4.5,
  'horsepower': 161.0,
  'mpg': 12.4,
  'color': 'Unknown',
  'image': '',
  'seats': 7,
  'variant': 'XT',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 2,
  'name': 'Tata Safari',
  'make': 'Tata',
  'model': 'Safari',
  'year': 2024,
  'price': 4852655,
  'mileage': 16.9,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'DCT',
  'safetyRating': 4.0,
  'horsepower': 178.9,
  'mpg': 16.9,
  'color': 'Unknown',
  'image': '',
  'seats': 7,
  'variant': 'XE',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 3,
  'name': 'BMW X1',
  'make': 'BMW',
  'model': 'X1',
  'year': 2024,
  'price': 6881015,
  'mileage': 13.8,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 4.5,
  'horsepower': 87.5,
  'mpg': 13.8,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'M Sport',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 4,
  'name': 'Hyundai Creta',
  'make': 'Hyundai',
  'model': 'Creta',
  'year': 2024,
  'price': 4256100,
  'mileage': 17.4,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'Manual',
  'safetyRating': 4.5,
  'horsepower': 85.0,
  'mpg': 17.4,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'Magna',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 5,
  'name': 'Honda Elevate',
  'make': 'Honda',
  'model': 'Elevate',
  'year': 2024,
  'price': 1057783,
  'mileage': 13.9,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'Automatic',
  'safetyRating': 4.5,
  'horsepower': 136.3,
  'mpg': 13.9,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'S',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 6,
  'name': 'Honda CR-V',
  'make': 'Honda',
  'model': 'CR-V',
  'year': 2024,
  'price': 2705550,
  'mileage': 14.7,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'Automatic',
  'safetyRating': 4.0,
  'horsepower': 119.7,
  'mpg': 14.7,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'V',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 7,
  'name': 'Toyota Camry',
  'make': 'Toyota',
  'model': 'Camry',
  'year': 2024,
  'price': 6978523,
  'mileage': 16.1,
  'bodyType': 'Hatchback',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 4.0,
  'horsepower': 139.8,
  'mpg': 16.1,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'G',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 8,
  'name': 'Hyundai Alcazar',
  'make': 'Hyundai',
  'model': 'Alcazar',
  'year': 2024,
  'price': 1179304,
  'mileage': 16.9,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'CVT',
  'safetyRating': 4.0,
  'horsepower': 86.8,
  'mpg': 16.9,
  'color': 'Unknown',
  'image': '',
  'seats': 8,
  'variant': 'Asta',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 9,
  'name': 'Honda Civic',
  'make': 'Honda',
  'model': 'Civic',
  'year': 2024,
  'price': 5919115,
  'mileage': 14.3,
  'bodyType': 'Sedan',
  'fuelType': 'Petrol',
  'transmission': 'Automatic',
  'safetyRating': 3.0,
  'horsepower': 209.1,
  'mpg': 14.3,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'VX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 10,
  'name': 'Hyundai Tucson',
  'make': 'Hyundai',
  'model': 'Tucson',
  'year': 2024,
  'price': 2831401,
  'mileage': 16.2,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 5.0,
  'horsepower': 105.0,
  'mpg': 16.2,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'Magna',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 11,
  'name': 'Tata Safari',
  'make': 'Tata',
  'model': 'Safari',
  'year': 2024,
  'price': 3206434,
  'mileage': 16.7,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'Automatic',
  'safetyRating': 4.0,
  'horsepower': 114.3,
  'mpg': 16.7,
  'color': 'Unknown',
  'image': '',
  'seats': 8,
  'variant': 'XM',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 12,
  'name': 'Tata Altroz',
  'make': 'Tata',
  'model': 'Altroz',
  'year': 2024,
  'price': 5627362,
  'mileage': 12.6,
  'bodyType': 'Sedan',
  'fuelType': 'Petrol',
  'transmission': 'CVT',
  'safetyRating': 4.0,
  'horsepower': 200.0,
  'mpg': 12.6,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'XZ+ #Dark',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 13,
  'name': 'Hyundai Tucson',
  'make': 'Hyundai',
  'model': 'Tucson',
  'year': 2024,
  'price': 1035300,
  'mileage': 13.4,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'CVT',
  'safetyRating': 5.0,
  'horsepower': 246.9,
  'mpg': 13.4,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'SX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 14,
  'name': 'Tata Safari',
  'make': 'Tata',
  'model': 'Safari',
  'year': 2024,
  'price': 4529035,
  'mileage': 15.0,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'Automatic',
  'safetyRating': 3.0,
  'horsepower': 165.9,
  'mpg': 15.0,
  'color': 'Unknown',
  'image': '',
  'seats': 7,
  'variant': 'XZ+ #Dark',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 15,
  'name': 'Tata Nexon EV',
  'make': 'Tata',
  'model': 'Nexon EV',
  'year': 2024,
  'price': 1773822,
  'mileage': 5.9,
  'bodyType': 'Sedan',
  'fuelType': 'Electric',
  'transmission': 'Automatic',
  'safetyRating': 3.0,
  'horsepower': 335.0,
  'mpg': 5.9,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'XZ+ #Dark',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 16,
  'name': 'BMW 3 Series',
  'make': 'BMW',
  'model': '3 Series',
  'year': 2024,
  'price': 942854,
  'mileage': 16.8,
  'bodyType': 'Sedan',
  'fuelType': 'Petrol',
  'transmission': 'Manual',
  'safetyRating': 5.0,
  'horsepower': 229.3,
  'mpg': 16.8,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'Luxury Line',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 17,
  'name': 'Toyota Camry',
  'make': 'Toyota',
  'model': 'Camry',
  'year': 2024,
  'price': 3096612,
  'mileage': 15.9,
  'bodyType': 'Sedan',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 4.5,
  'horsepower': 249.1,
  'mpg': 15.9,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'VX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 18,
  'name': 'Tata Nexon',
  'make': 'Tata',
  'model': 'Nexon',
  'year': 2024,
  'price': 5026462,
  'mileage': 14.1,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 3.0,
  'horsepower': 129.2,
  'mpg': 14.1,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'XZ',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 19,
  'name': 'BMW X1',
  'make': 'BMW',
  'model': 'X1',
  'year': 2024,
  'price': 4338570,
  'mileage': 13.3,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'DCT',
  'safetyRating': 4.0,
  'horsepower': 124.5,
  'mpg': 13.3,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'xDrive20i',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 20,
  'name': 'Tata Nexon EV',
  'make': 'Tata',
  'model': 'Nexon EV',
  'year': 2024,
  'price': 4227433,
  'mileage': 5.8,
  'bodyType': 'Sedan',
  'fuelType': 'Electric',
  'transmission': 'Automatic',
  'safetyRating': 4.0,
  'horsepower': 140.0,
  'mpg': 5.8,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'XZ+ #Dark',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 21,
  'name': 'Hyundai Verna',
  'make': 'Hyundai',
  'model': 'Verna',
  'year': 2024,
  'price': 2922676,
  'mileage': 15.0,
  'bodyType': 'Hatchback',
  'fuelType': 'Petrol',
  'transmission': 'CVT',
  'safetyRating': 4.5,
  'horsepower': 212.1,
  'mpg': 15.0,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'SX(O)',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 22,
  'name': 'Toyota RAV4',
  'make': 'Toyota',
  'model': 'RAV4',
  'year': 2024,
  'price': 3998339,
  'mileage': 17.3,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 3.0,
  'horsepower': 90.3,
  'mpg': 17.3,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'VX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 23,
  'name': 'Hyundai Verna',
  'make': 'Hyundai',
  'model': 'Verna',
  'year': 2024,
  'price': 7240670,
  'mileage': 15.8,
  'bodyType': 'Hatchback',
  'fuelType': 'Petrol',
  'transmission': 'DCT',
  'safetyRating': 4.0,
  'horsepower': 154.9,
  'mpg': 15.8,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'Asta',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 24,
  'name': 'BMW i4',
  'make': 'BMW',
  'model': 'i4',
  'year': 2024,
  'price': 6712337,
  'mileage': 6.8,
  'bodyType': 'Sedan',
  'fuelType': 'Electric',
  'transmission': 'Automatic',
  'safetyRating': 4.5,
  'horsepower': 170.0,
  'mpg': 6.8,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'xDrive20i',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 25,
  'name': 'BMW 3 Series',
  'make': 'BMW',
  'model': '3 Series',
  'year': 2024,
  'price': 6495996,
  'mileage': 15.4,
  'bodyType': 'Hatchback',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 5.0,
  'horsepower': 240.4,
  'mpg': 15.4,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'M Sport',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 26,
  'name': 'Toyota Prius',
  'make': 'Toyota',
  'model': 'Prius',
  'year': 2024,
  'price': 4507413,
  'mileage': 16.8,
  'bodyType': 'Sedan',
  'fuelType': 'Diesel',
  'transmission': 'CVT',
  'safetyRating': 4.0,
  'horsepower': 211.2,
  'mpg': 16.8,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'VX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 27,
  'name': 'Toyota Prius',
  'make': 'Toyota',
  'model': 'Prius',
  'year': 2024,
  'price': 2087607,
  'mileage': 12.7,
  'bodyType': 'Hatchback',
  'fuelType': 'Petrol',
  'transmission': 'DCT',
  'safetyRating': 5.0,
  'horsepower': 245.5,
  'mpg': 12.7,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'G',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 28,
  'name': 'BMW i4',
  'make': 'BMW',
  'model': 'i4',
  'year': 2024,
  'price': 2324473,
  'mileage': 5.6,
  'bodyType': 'Sedan',
  'fuelType': 'Electric',
  'transmission': 'Automatic',
  'safetyRating': 5.0,
  'horsepower': 170.0,
  'mpg': 5.6,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'Luxury Line',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 29,
  'name': 'Hyundai Tucson',
  'make': 'Hyundai',
  'model': 'Tucson',
  'year': 2024,
  'price': 993281,
  'mileage': 12.0,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'CVT',
  'safetyRating': 5.0,
  'horsepower': 122.1,
  'mpg': 12.0,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'Sportz',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 30,
  'name': 'Hyundai Verna',
  'make': 'Hyundai',
  'model': 'Verna',
  'year': 2024,
  'price': 5452841,
  'mileage': 15.6,
  'bodyType': 'Hatchback',
  'fuelType': 'Diesel',
  'transmission': 'Manual',
  'safetyRating': 4.5,
  'horsepower': 217.4,
  'mpg': 15.6,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'Magna',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 31,
  'name': 'Honda Amaze',
  'make': 'Honda',
  'model': 'Amaze',
  'year': 2024,
  'price': 6283965,
  'mileage': 17.5,
  'bodyType': 'Hatchback',
  'fuelType': 'Diesel',
  'transmission': 'CVT',
  'safetyRating': 4.5,
  'horsepower': 170.8,
  'mpg': 17.5,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'S',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 32,
  'name': 'Toyota RAV4',
  'make': 'Toyota',
  'model': 'RAV4',
  'year': 2024,
  'price': 4359433,
  'mileage': 18.4,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'Manual',
  'safetyRating': 4.5,
  'horsepower': 215.6,
  'mpg': 18.4,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'ZX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 33,
  'name': 'Toyota Camry',
  'make': 'Toyota',
  'model': 'Camry',
  'year': 2024,
  'price': 6416649,
  'mileage': 13.5,
  'bodyType': 'Hatchback',
  'fuelType': 'Petrol',
  'transmission': 'Manual',
  'safetyRating': 5.0,
  'horsepower': 176.1,
  'mpg': 13.5,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'V',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 34,
  'name': 'Hyundai Alcazar',
  'make': 'Hyundai',
  'model': 'Alcazar',
  'year': 2024,
  'price': 1055096,
  'mileage': 16.2,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'CVT',
  'safetyRating': 5.0,
  'horsepower': 134.6,
  'mpg': 16.2,
  'color': 'Unknown',
  'image': '',
  'seats': 7,
  'variant': 'SX(O)',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 35,
  'name': 'BMW X3',
  'make': 'BMW',
  'model': 'X3',
  'year': 2024,
  'price': 5592452,
  'mileage': 17.5,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'CVT',
  'safetyRating': 3.0,
  'horsepower': 86.7,
  'mpg': 17.5,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'sDrive20d',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 36,
  'name': 'BMW i4',
  'make': 'BMW',
  'model': 'i4',
  'year': 2024,
  'price': 5300904,
  'mileage': 5.9,
  'bodyType': 'Sedan',
  'fuelType': 'Electric',
  'transmission': 'Automatic',
  'safetyRating': 3.0,
  'horsepower': 200.0,
  'mpg': 5.9,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'xDrive20i',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 37,
  'name': 'Toyota RAV4',
  'make': 'Toyota',
  'model': 'RAV4',
  'year': 2024,
  'price': 6148452,
  'mileage': 11.5,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 4.5,
  'horsepower': 96.1,
  'mpg': 11.5,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'G',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 38,
  'name': 'Tata Harrier',
  'make': 'Tata',
  'model': 'Harrier',
  'year': 2024,
  'price': 1165497,
  'mileage': 14.4,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'Manual',
  'safetyRating': 3.0,
  'horsepower': 174.5,
  'mpg': 14.4,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'XZ',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 39,
  'name': 'Honda Elevate',
  'make': 'Honda',
  'model': 'Elevate',
  'year': 2024,
  'price': 3214262,
  'mileage': 13.4,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 5.0,
  'horsepower': 181.1,
  'mpg': 13.4,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'VX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 40,
  'name': 'Toyota Prius',
  'make': 'Toyota',
  'model': 'Prius',
  'year': 2024,
  'price': 1045909,
  'mileage': 14.0,
  'bodyType': 'Sedan',
  'fuelType': 'Petrol',
  'transmission': 'Manual',
  'safetyRating': 4.0,
  'horsepower': 153.6,
  'mpg': 14.0,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'G',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 41,
  'name': 'Toyota Camry',
  'make': 'Toyota',
  'model': 'Camry',
  'year': 2024,
  'price': 4049844,
  'mileage': 14.4,
  'bodyType': 'Sedan',
  'fuelType': 'Diesel',
  'transmission': 'Manual',
  'safetyRating': 3.0,
  'horsepower': 153.0,
  'mpg': 14.4,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'V',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 42,
  'name': 'Toyota Corolla',
  'make': 'Toyota',
  'model': 'Corolla',
  'year': 2024,
  'price': 3065045,
  'mileage': 17.8,
  'bodyType': 'Hatchback',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 4.5,
  'horsepower': 125.6,
  'mpg': 17.8,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'VX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 43,
  'name': 'Hyundai i20',
  'make': 'Hyundai',
  'model': 'i20',
  'year': 2024,
  'price': 5169337,
  'mileage': 17.2,
  'bodyType': 'Hatchback',
  'fuelType': 'Diesel',
  'transmission': 'CVT',
  'safetyRating': 3.0,
  'horsepower': 212.5,
  'mpg': 17.2,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'Sportz',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 44,
  'name': 'Honda Elevate',
  'make': 'Honda',
  'model': 'Elevate',
  'year': 2024,
  'price': 1908961,
  'mileage': 11.6,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 3.0,
  'horsepower': 212.2,
  'mpg': 11.6,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'S',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 45,
  'name': 'BMW 3 Series',
  'make': 'BMW',
  'model': '3 Series',
  'year': 2024,
  'price': 4178465,
  'mileage': 11.6,
  'bodyType': 'Sedan',
  'fuelType': 'Petrol',
  'transmission': 'Manual',
  'safetyRating': 5.0,
  'horsepower': 154.2,
  'mpg': 11.6,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'M Sport',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 46,
  'name': 'Hyundai Verna',
  'make': 'Hyundai',
  'model': 'Verna',
  'year': 2024,
  'price': 1233808,
  'mileage': 18.0,
  'bodyType': 'Hatchback',
  'fuelType': 'Diesel',
  'transmission': 'CVT',
  'safetyRating': 4.5,
  'horsepower': 117.2,
  'mpg': 18.0,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'SX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 47,
  'name': 'Toyota Camry',
  'make': 'Toyota',
  'model': 'Camry',
  'year': 2024,
  'price': 6316525,
  'mileage': 15.5,
  'bodyType': 'Hatchback',
  'fuelType': 'Diesel',
  'transmission': 'DCT',
  'safetyRating': 3.0,
  'horsepower': 103.5,
  'mpg': 15.5,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'VX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 48,
  'name': 'Toyota RAV4',
  'make': 'Toyota',
  'model': 'RAV4',
  'year': 2024,
  'price': 6393015,
  'mileage': 12.8,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'Automatic',
  'safetyRating': 3.0,
  'horsepower': 103.0,
  'mpg': 12.8,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'VX',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 49,
  'name': 'Honda Elevate',
  'make': 'Honda',
  'model': 'Elevate',
  'year': 2024,
  'price': 5235853,
  'mileage': 13.3,
  'bodyType': 'SUV',
  'fuelType': 'Petrol',
  'transmission': 'DCT',
  'safetyRating': 5.0,
  'horsepower': 232.7,
  'mpg': 13.3,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'V',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
  {
  'id': 50,
  'name': 'BMW X3',
  'make': 'BMW',
  'model': 'X3',
  'year': 2024,
  'price': 5717952,
  'mileage': 12.6,
  'bodyType': 'SUV',
  'fuelType': 'Diesel',
  'transmission': 'Manual',
  'safetyRating': 4.0,
  'horsepower': 194.5,
  'mpg': 12.6,
  'color': 'Unknown',
  'image': '',
  'seats': 5,
  'variant': 'M Sport',
  'matchPercentage': 0,
  'scoreBreakdown': {
    'budget': 0,
    'efficiency': 0,
    'safety': 0
  }
},
]
